#!/bin/sh

function build_regex() {
  types=('build' 'docs' 'feat' 'fix' 'perf' 'refactor' 'style' 'test' 'chore')

  regexp="^[.0-9]+$|"

  regexp="${regexp}^([Rr]evert|[Mm]erge|[Ff]ixup!)? .*$|^("

  for type in "${types[@]}"
  do
    regexp="${regexp}$type|"
  done

  regexp="${regexp%|})(\(.+\))?: "
}

build_regex

INPUT=$1
commit_message=$(head -n1 "$INPUT")

function print_error() {
  echo -e "\n\e[31m[Невалидный формат коммита]"
  echo -e "------------------------\033[0m\e[0m"
  echo -e "Допустимые типы коммита: \e[36m${types[@]}\033[0m"
  echo -e "\e[37mВведённое сообщение: \e[33m\"$commit_message\"\033[0m"
  echo -e "\e[37mПример корректного сообщения: \e[36m\"fix(subject): message\"\033[0m"
  echo -e "\e[37mRegex: \e[33m\"$regexp\"\033[0m"
}

if [[ ! "$commit_message" =~ $regexp ]]; then
  print_error
  exit 1
fi